version: '2'
services:
  spring_boot_jee:
    build: /home/mypc/dev/java/spring_boot_tutorial/
    ports:
      - "8080:8080"
# In bridge mode this is not allowed.
#    links:
#      - "pgsql:spring_boot_db"
    networks:
      - jee_db
#      - jee_elk

  pgsql:
    build: /home/mypc/dev/tools/docker/docker_network/postgres
    volumes:
      - /home/mypc/dev/tools/docker/docker_network/postgres/pgdata:/var/lib/postgresql/data/pgdata_volume
    networks:
      - jee_db

  logstash:
    build: /home/mypc/dev/tools/docker/docker_network/logstash
    ports:
        - "5555:5555"
    networks:
        - elk
  elasticsearch:
    build: /home/mypc/dev/tools/docker/docker_network/elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
        - "9200:9200"
    networks:
        - elk

networks:
  jee_db:
    driver: bridge
  elk:
    driver: bridge

volumes:
  esdata1:
    driver: local
