version: '2'
services:
  spring_boot_jee:
    build: /home/mypc/dev/java/spring_boot_tutorial/
    ports:
      - "8080:8080"
# In bridge mode this is not allowed.
#    links:
#      - "pgsql:spring_boot_db"
    networks:
      - jee_db
#      - jee_elk

  pgsql:
    build: /home/mypc/dev/tools/docker/docker_network/postgres
    volumes:
      - /home/mypc/dev/tools/docker/docker_network/postgres/pgdata:/var/lib/postgresql/data/pgdata_volume
    networks:
      - jee_db

  logstash:
    build: /home/mypc/dev/tools/docker/docker_network/logstash
    ports:
        - "5044:5044"
    networks:
        - elk

networks:
  jee_db:
    driver: bridge
  elk:
    driver: bridge

